//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarWashApp.Entities
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    
    public partial class Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.Order = new HashSet<Order>();
        }
    
        public int ID { get; set; }
        public string CarStateNumber { get; set; }
        public string ClientFullName { get; set; }
        public string PhoneNumber { get; set; }
        public int CarTypeID { get; set; }
    
        public virtual CarType CarType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Order { get; set; }

        public String CarType_Bind
        {
            get
            {
                return CarType?.CarTypeName;
            }
        }

        public String ClientFullNameWithInitials
        {
            get
            {
                List<String> parts = ClientFullName.Trim().Split(' ').ToList();

                return $"{parts[0]} {parts[1][0]}. {parts[2][0]}.";
            }
        }
    }
}
